name: Main AU
run-name: Market (AU) Check 🚀
on:
  schedule:
  # 02:30am (UTC)
    - cron:  '30 2 * * 1-5'
  workflow_dispatch:

jobs:
  Call-Pre-Workflow:
    uses: ./.github/workflows/watchlist-validator.yml
    with:
      trigger: true
    runs-on: ubuntu-latest

  AU-Market-Check-Action:
    needs: Call-Pre-Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print start time
        run: echo "The start time is $(date)"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Initialise Prisma Client
        run: |
          prisma generate

      - name: Run script 
        run: python main.py watchlist-au.json # this will outputs a new file (metadata.json)
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }} 
          PRIMARY_RECEPIENT: ${{ vars.PRIMARY_RECEPIENT }}
          DEBUG_RECEPIENT: ${{ vars.DEBUG_RECEPIENT }} 
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 

      - name: Save artefact
        uses: actions/upload-artifact@v4
        with:
          name: metadata
          path: metadata.json
          overwrite: true

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install node dependencies
        run: npm install

      - name: Run script 
        run: npm run email # this will consume the metadata.json file
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }} 
          PRIMARY_RECEPIENT: ${{ vars.PRIMARY_RECEPIENT }}

      - name: Print end time
        run: echo "The end time is $(date)"


      
